### ISSUE TITLE
The Search by Image's "popup" is unreadable when using a dark GTK Theme on Linux - Here how to fix it

### ISSUE THREAD

**Issue by hasB4K** [dessant/search-by-image#38]
Hi,

Since you fixed this issue: https://github.com/dessant/view-page-archive/issues/2 - I checked your other amazing addons :). I will definitely use this one! This add-on has the same issue, so for the record here the description of it:

I am using a Dark GTK Theme on Linux with Firefox. And sadly, it is quite difficult to use this plugin since the background color of the popup is almost black with this setup.

After seeing the `src/action/App.vue`, line 239, I would assume you just need to add the following property:

```css
body
{
    background-color: #FFFFFF !important;
}
```

Sadly, I did not directly tested that since it became harder to modify an extension on Firefox (lack of time mostly). However I modified my `userContent.css` in the profile folder of Firefox: `~/.mozilla/firefox/XXXXXXXXXX.default/chrome`, and it works:

```css
@-moz-document url("moz-extension://[...extension-hash...]/src/action/index.html")
{
    body
    {
        background-color: #FFFFFF !important;
    }
}
```

Thank you for your great add-on!

Best regards,
